2020-02-17 10:45:42,972 ERROR: Exception on /explore [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 126, in explore
    posts = Post.query.order_by(Post.timestamp()).all()
TypeError: 'InstrumentedAttribute' object is not callable
2020-02-17 10:45:53,288 ERROR: Exception on /explore [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 126, in explore
    posts = Post.query.order_by(Post.timestamp()).all()
TypeError: 'InstrumentedAttribute' object is not callable
2020-02-17 10:47:25,664 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-17 10:48:52,978 ERROR: Exception on /explore [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 126, in explore
    posts = Post.query.order_by(Post.timestamp()).all()
TypeError: 'InstrumentedAttribute' object is not callable
2020-02-17 10:49:08,653 ERROR: Exception on /explore [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 126, in explore
    posts = Post.query.order_by(Post.timestamp()).all()
TypeError: 'InstrumentedAttribute' object is not callable
2020-02-17 10:52:04,309 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-17 10:52:09,519 ERROR: Exception on /explore [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 126, in explore
    posts = Post.query.order_by(Post.timestamp()).all()
TypeError: 'InstrumentedAttribute' object is not callable
2020-02-17 10:58:13,638 ERROR: Exception on /explore [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 126, in explore
    posts = Post.query.order_by(Post.timestamp()).all()
TypeError: 'InstrumentedAttribute' object is not callable
2020-02-17 10:58:19,937 ERROR: Exception on /explore [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 126, in explore
    posts = Post.query.order_by(Post.timestamp()).all()
TypeError: 'InstrumentedAttribute' object is not callable
2020-02-17 10:58:30,164 ERROR: Exception on /explore [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 126, in explore
    posts = Post.query.order_by(Post.timestamp()).all()
TypeError: 'InstrumentedAttribute' object is not callable
2020-02-17 10:59:53,676 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
