2020-02-17 12:09:26,116 ERROR: Exception on /explore [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 36, in explore
    return render_template('index.html', title='Explore', posts=posts.items, next_url=next_url, prev_url=prev_url)
NameError: name 'next_url' is not defined
2020-02-17 12:12:20,558 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-17 12:12:28,545 ERROR: Exception on /explore [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 38, in explore
    'index.html', title='Explore', posts=posts.items, next_url=next_url, prev_url=prev_url)
NameError: name 'next_url' is not defined
2020-02-17 12:12:33,635 ERROR: Exception on /explore [GET] [in c:\v_playground\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\v_playground\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\v_playground\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\v_playground\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\v_playground\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\GH\microblog\app\routes.py", line 38, in explore
    'index.html', title='Explore', posts=posts.items, next_url=next_url, prev_url=prev_url)
NameError: name 'next_url' is not defined
2020-02-17 12:44:04,251 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:41]
2020-02-18 14:03:46,882 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:42]
2020-02-18 14:12:44,271 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:42]
2020-02-18 14:19:48,888 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:42]
2020-02-18 14:39:27,116 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:42]
2020-02-19 11:42:22,915 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:42]
2020-02-19 11:46:48,860 INFO: Microblog startup [in C:\GH\microblog\app\__init__.py:42]
